// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/nonce/v1/nonce.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/nonce module.
type Params struct {
	// past_window_us is how far in the past (microseconds) a timestamp nonce can be
	// relative to block time. Default: 300000000 (5 minutes).
	PastWindowUs uint64 `protobuf:"varint,1,opt,name=past_window_us,json=pastWindowUs,proto3" json:"past_window_us,omitempty"`
	// future_window_us is how far in the future (microseconds) a timestamp nonce can be
	// relative to block time. Default: 300000000 (5 minutes).
	FutureWindowUs uint64 `protobuf:"varint,2,opt,name=future_window_us,json=futureWindowUs,proto3" json:"future_window_us,omitempty"`
	// timestamp_nonce_cutoff is the sequence value threshold. Values >= this are
	// treated as timestamp nonces (microseconds). Fixed at 2^40; stored for
	// serialization but not governance-configurable (protocol constant).
	TimestampNonceCutoff uint64 `protobuf:"varint,3,opt,name=timestamp_nonce_cutoff,json=timestampNonceCutoff,proto3" json:"timestamp_nonce_cutoff,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe061dd1d5bcaa9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPastWindowUs() uint64 {
	if m != nil {
		return m.PastWindowUs
	}
	return 0
}

func (m *Params) GetFutureWindowUs() uint64 {
	if m != nil {
		return m.FutureWindowUs
	}
	return 0
}

func (m *Params) GetTimestampNonceCutoff() uint64 {
	if m != nil {
		return m.TimestampNonceCutoff
	}
	return 0
}

// NonceEntry represents a consumed timestamp nonce for genesis export/import.
type NonceEntry struct {
	// timestamp_us is the nonce value in microseconds since Unix epoch.
	TimestampUs uint64 `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	// address is the bech32-encoded account address that consumed this nonce.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *NonceEntry) Reset()         { *m = NonceEntry{} }
func (m *NonceEntry) String() string { return proto.CompactTextString(m) }
func (*NonceEntry) ProtoMessage()    {}
func (*NonceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe061dd1d5bcaa9, []int{1}
}
func (m *NonceEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NonceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NonceEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NonceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceEntry.Merge(m, src)
}
func (m *NonceEntry) XXX_Size() int {
	return m.Size()
}
func (m *NonceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NonceEntry proto.InternalMessageInfo

func (m *NonceEntry) GetTimestampUs() uint64 {
	if m != nil {
		return m.TimestampUs
	}
	return 0
}

func (m *NonceEntry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "gaia.nonce.v1.Params")
	proto.RegisterType((*NonceEntry)(nil), "gaia.nonce.v1.NonceEntry")
}

func init() { proto.RegisterFile("gaia/nonce/v1/nonce.proto", fileDescriptor_6fe061dd1d5bcaa9) }

var fileDescriptor_6fe061dd1d5bcaa9 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x4f, 0xcc, 0x4c,
	0xd4, 0xcf, 0xcb, 0xcf, 0x4b, 0x4e, 0xd5, 0x2f, 0x33, 0x84, 0x30, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x78, 0x41, 0x52, 0x7a, 0x10, 0x91, 0x32, 0x43, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c,
	0xb0, 0x8c, 0x3e, 0x88, 0x05, 0x51, 0x24, 0x25, 0x99, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0x1c, 0x0f,
	0x91, 0x80, 0x70, 0xa0, 0x52, 0x82, 0x89, 0xb9, 0x99, 0x79, 0xf9, 0xfa, 0x60, 0x12, 0x22, 0xa4,
	0xb4, 0x86, 0x91, 0x8b, 0x2d, 0x20, 0xb1, 0x28, 0x31, 0xb7, 0x58, 0x48, 0x85, 0x8b, 0xaf, 0x20,
	0xb1, 0xb8, 0x24, 0xbe, 0x3c, 0x33, 0x2f, 0x25, 0xbf, 0x3c, 0xbe, 0xb4, 0x58, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x25, 0x88, 0x07, 0x24, 0x1a, 0x0e, 0x16, 0x0c, 0x2d, 0x16, 0xd2, 0xe0, 0x12, 0x48,
	0x2b, 0x2d, 0x29, 0x2d, 0x4a, 0x45, 0x52, 0xc7, 0x04, 0x56, 0xc7, 0x07, 0x11, 0x87, 0xab, 0x34,
	0xe1, 0x12, 0x2b, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x88, 0x07, 0x3b, 0x3a, 0x3e,
	0xb9, 0xb4, 0x24, 0x3f, 0x2d, 0x4d, 0x82, 0x19, 0xac, 0x5e, 0x04, 0x2e, 0xeb, 0x07, 0x92, 0x74,
	0x06, 0xcb, 0x59, 0xc9, 0xbc, 0x58, 0x20, 0xcf, 0xd8, 0xf5, 0x7c, 0x83, 0x96, 0x30, 0x38, 0x1c,
	0x2a, 0xa0, 0x21, 0x01, 0x71, 0xa3, 0x52, 0x32, 0x17, 0x17, 0x58, 0xb1, 0x6b, 0x5e, 0x49, 0x51,
	0xa5, 0x90, 0x22, 0x17, 0x0f, 0xc2, 0x06, 0xb8, 0x7b, 0xb9, 0xe1, 0x62, 0xa1, 0xc5, 0x42, 0x46,
	0x5c, 0xec, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0x10, 0x57, 0x72, 0x3a, 0x49, 0x5c, 0xda, 0xa2,
	0x2b, 0x02, 0x0d, 0x15, 0x47, 0x88, 0x4c, 0x70, 0x49, 0x51, 0x66, 0x5e, 0x7a, 0x10, 0x4c, 0xa1,
	0x93, 0xdd, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1,
	0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xa9, 0xa4, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x42, 0x43, 0x56, 0x1f, 0xc5, 0x95, 0x25, 0x95, 0x05,
	0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0xa0, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0xa9, 0x4e,
	0xaf, 0xca, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PastWindowUs != that1.PastWindowUs {
		return false
	}
	if this.FutureWindowUs != that1.FutureWindowUs {
		return false
	}
	if this.TimestampNonceCutoff != that1.TimestampNonceCutoff {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimestampNonceCutoff != 0 {
		i = encodeVarintNonce(dAtA, i, uint64(m.TimestampNonceCutoff))
		i--
		dAtA[i] = 0x18
	}
	if m.FutureWindowUs != 0 {
		i = encodeVarintNonce(dAtA, i, uint64(m.FutureWindowUs))
		i--
		dAtA[i] = 0x10
	}
	if m.PastWindowUs != 0 {
		i = encodeVarintNonce(dAtA, i, uint64(m.PastWindowUs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NonceEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NonceEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NonceEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintNonce(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.TimestampUs != 0 {
		i = encodeVarintNonce(dAtA, i, uint64(m.TimestampUs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNonce(dAtA []byte, offset int, v uint64) int {
	offset -= sovNonce(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PastWindowUs != 0 {
		n += 1 + sovNonce(uint64(m.PastWindowUs))
	}
	if m.FutureWindowUs != 0 {
		n += 1 + sovNonce(uint64(m.FutureWindowUs))
	}
	if m.TimestampNonceCutoff != 0 {
		n += 1 + sovNonce(uint64(m.TimestampNonceCutoff))
	}
	return n
}

func (m *NonceEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimestampUs != 0 {
		n += 1 + sovNonce(uint64(m.TimestampUs))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovNonce(uint64(l))
	}
	return n
}

func sovNonce(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNonce(x uint64) (n int) {
	return sovNonce(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNonce
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PastWindowUs", wireType)
			}
			m.PastWindowUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PastWindowUs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FutureWindowUs", wireType)
			}
			m.FutureWindowUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FutureWindowUs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampNonceCutoff", wireType)
			}
			m.TimestampNonceCutoff = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampNonceCutoff |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNonce(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNonce
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NonceEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNonce
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NonceEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NonceEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampUs", wireType)
			}
			m.TimestampUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampUs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNonce
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNonce
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNonce(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNonce
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNonce(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNonce
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNonce
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNonce
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNonce
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNonce
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNonce        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNonce          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNonce = fmt.Errorf("proto: unexpected end of group")
)
