// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/nonce/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryHasNonceRequest struct {
	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TimestampUs uint64 `protobuf:"varint,2,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
}

func (m *QueryHasNonceRequest) Reset()         { *m = QueryHasNonceRequest{} }
func (m *QueryHasNonceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryHasNonceRequest) ProtoMessage()    {}
func (*QueryHasNonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{2}
}
func (m *QueryHasNonceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHasNonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHasNonceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHasNonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHasNonceRequest.Merge(m, src)
}
func (m *QueryHasNonceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryHasNonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHasNonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHasNonceRequest proto.InternalMessageInfo

func (m *QueryHasNonceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryHasNonceRequest) GetTimestampUs() uint64 {
	if m != nil {
		return m.TimestampUs
	}
	return 0
}

type QueryHasNonceResponse struct {
	HasNonce bool `protobuf:"varint,1,opt,name=has_nonce,json=hasNonce,proto3" json:"has_nonce,omitempty"`
}

func (m *QueryHasNonceResponse) Reset()         { *m = QueryHasNonceResponse{} }
func (m *QueryHasNonceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryHasNonceResponse) ProtoMessage()    {}
func (*QueryHasNonceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{3}
}
func (m *QueryHasNonceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHasNonceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHasNonceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHasNonceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHasNonceResponse.Merge(m, src)
}
func (m *QueryHasNonceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryHasNonceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHasNonceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHasNonceResponse proto.InternalMessageInfo

func (m *QueryHasNonceResponse) GetHasNonce() bool {
	if m != nil {
		return m.HasNonce
	}
	return false
}

type QueryNoncesByAddressRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryNoncesByAddressRequest) Reset()         { *m = QueryNoncesByAddressRequest{} }
func (m *QueryNoncesByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNoncesByAddressRequest) ProtoMessage()    {}
func (*QueryNoncesByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{4}
}
func (m *QueryNoncesByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNoncesByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNoncesByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNoncesByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNoncesByAddressRequest.Merge(m, src)
}
func (m *QueryNoncesByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNoncesByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNoncesByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNoncesByAddressRequest proto.InternalMessageInfo

func (m *QueryNoncesByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryNoncesByAddressResponse struct {
	TimestampNonces []uint64 `protobuf:"varint,1,rep,packed,name=timestamp_nonces,json=timestampNonces,proto3" json:"timestamp_nonces,omitempty"`
}

func (m *QueryNoncesByAddressResponse) Reset()         { *m = QueryNoncesByAddressResponse{} }
func (m *QueryNoncesByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNoncesByAddressResponse) ProtoMessage()    {}
func (*QueryNoncesByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7adea647a9e7f9c, []int{5}
}
func (m *QueryNoncesByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNoncesByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNoncesByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNoncesByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNoncesByAddressResponse.Merge(m, src)
}
func (m *QueryNoncesByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNoncesByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNoncesByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNoncesByAddressResponse proto.InternalMessageInfo

func (m *QueryNoncesByAddressResponse) GetTimestampNonces() []uint64 {
	if m != nil {
		return m.TimestampNonces
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "gaia.nonce.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "gaia.nonce.v1.QueryParamsResponse")
	proto.RegisterType((*QueryHasNonceRequest)(nil), "gaia.nonce.v1.QueryHasNonceRequest")
	proto.RegisterType((*QueryHasNonceResponse)(nil), "gaia.nonce.v1.QueryHasNonceResponse")
	proto.RegisterType((*QueryNoncesByAddressRequest)(nil), "gaia.nonce.v1.QueryNoncesByAddressRequest")
	proto.RegisterType((*QueryNoncesByAddressResponse)(nil), "gaia.nonce.v1.QueryNoncesByAddressResponse")
}

func init() { proto.RegisterFile("gaia/nonce/v1/query.proto", fileDescriptor_c7adea647a9e7f9c) }

var fileDescriptor_c7adea647a9e7f9c = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xb4, 0x35, 0x26, 0xaf, 0x4a, 0x75, 0x4c, 0x30, 0x6e, 0xca, 0xb6, 0x19, 0x7b, 0x88,
	0x55, 0x76, 0x48, 0x2b, 0xe8, 0xa9, 0x60, 0x4e, 0x7a, 0xf1, 0xc7, 0x8a, 0x17, 0x2f, 0x65, 0x9a,
	0x0e, 0x9b, 0x05, 0x77, 0x67, 0x9b, 0xb7, 0x29, 0x86, 0xd2, 0x8b, 0x27, 0x8f, 0x82, 0x08, 0xfe,
	0x09, 0xde, 0xf4, 0xcf, 0xe8, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0x22, 0xf8, 0x6f, 0xc8, 0xce, 0x4c,
	0x13, 0xb3, 0x2e, 0xd5, 0x4b, 0xc8, 0xbc, 0xf7, 0xbd, 0xef, 0xfb, 0xf6, 0x7d, 0x3c, 0xb8, 0x11,
	0x88, 0x50, 0xf0, 0x58, 0xc5, 0x3d, 0xc9, 0x0f, 0x3b, 0xfc, 0x60, 0x28, 0x07, 0x23, 0x2f, 0x19,
	0xa8, 0x54, 0xd1, 0xcb, 0x59, 0xcb, 0xd3, 0x2d, 0xef, 0xb0, 0xe3, 0xd4, 0x02, 0x15, 0x28, 0xdd,
	0xe1, 0xd9, 0x3f, 0x03, 0x72, 0x56, 0x03, 0xa5, 0x82, 0x57, 0x92, 0x8b, 0x24, 0xe4, 0x22, 0x8e,
	0x55, 0x2a, 0xd2, 0x50, 0xc5, 0x68, 0xbb, 0xcd, 0x9e, 0xc2, 0x48, 0xa1, 0xa1, 0xcd, 0xf1, 0x3b,
	0x57, 0x45, 0x14, 0xc6, 0x8a, 0xeb, 0x5f, 0x5b, 0xca, 0xb9, 0x31, 0xda, 0xba, 0xc5, 0x6a, 0x40,
	0x9f, 0x65, 0xc3, 0x4f, 0xc5, 0x40, 0x44, 0xe8, 0xcb, 0x83, 0xa1, 0xc4, 0x94, 0x3d, 0x81, 0x6b,
	0x73, 0x55, 0x4c, 0x54, 0x8c, 0x92, 0xde, 0x87, 0x72, 0xa2, 0x2b, 0x0d, 0xb2, 0x4e, 0xda, 0xcb,
	0x5b, 0x75, 0x6f, 0xee, 0x5b, 0x3c, 0x03, 0xef, 0x56, 0x4f, 0xbe, 0xaf, 0x95, 0x3e, 0xfd, 0xfa,
	0xb2, 0x49, 0x7c, 0x8b, 0x67, 0xcf, 0xa1, 0xa6, 0x09, 0x1f, 0x0a, 0x7c, 0x9c, 0xa1, 0xad, 0x10,
	0x6d, 0xc0, 0x45, 0xb1, 0xbf, 0x3f, 0x90, 0x68, 0x28, 0xab, 0xfe, 0xd9, 0x93, 0xb6, 0xe0, 0x52,
	0x1a, 0x46, 0x12, 0x53, 0x11, 0x25, 0xbb, 0x43, 0x6c, 0x2c, 0xac, 0x93, 0xf6, 0x92, 0xbf, 0x3c,
	0xad, 0xbd, 0x40, 0x76, 0x17, 0xea, 0x39, 0x52, 0xeb, 0xb3, 0x09, 0xd5, 0xbe, 0xc0, 0x5d, 0xed,
	0x4b, 0xf3, 0x56, 0xfc, 0x4a, 0xdf, 0x82, 0xd8, 0x3d, 0x68, 0xea, 0x29, 0xfd, 0xc2, 0xee, 0xe8,
	0x81, 0x11, 0xfc, 0xa7, 0x23, 0xf6, 0x08, 0x56, 0x8b, 0x07, 0xad, 0xea, 0x2d, 0xb8, 0x32, 0x73,
	0xac, 0xb5, 0x33, 0x8a, 0xc5, 0xf6, 0x92, 0xbf, 0x32, 0xad, 0x9b, 0xd9, 0xad, 0xcf, 0x8b, 0x70,
	0x41, 0x73, 0x51, 0x84, 0xb2, 0xd9, 0x1a, 0x6d, 0xe5, 0x96, 0xf9, 0x77, 0x2c, 0x0e, 0x3b, 0x0f,
	0x62, 0x5c, 0x30, 0xf6, 0x36, 0x5b, 0xfc, 0x9b, 0xaf, 0x3f, 0xdf, 0x2f, 0x5c, 0xa7, 0x75, 0x3e,
	0x9f, 0xbc, 0x49, 0x83, 0x7e, 0x20, 0x50, 0x39, 0x5b, 0x1a, 0xbd, 0x59, 0x44, 0x9a, 0xcb, 0xc9,
	0xd9, 0x38, 0x1f, 0x64, 0xb5, 0x77, 0x66, 0xda, 0xdb, 0xb4, 0x93, 0xd3, 0x9e, 0x26, 0xc2, 0x8f,
	0xec, 0x46, 0x8f, 0xf9, 0xd1, 0x9f, 0x11, 0x1f, 0xd3, 0x8f, 0x04, 0x56, 0x72, 0xdb, 0xa5, 0x9b,
	0x45, 0xca, 0xc5, 0xd9, 0x39, 0xb7, 0xff, 0x0b, 0x6b, 0xcd, 0xde, 0x99, 0x99, 0x6d, 0xd1, 0x35,
	0x5e, 0x70, 0x22, 0x38, 0x73, 0xda, 0xdd, 0x39, 0x19, 0xbb, 0xe4, 0x74, 0xec, 0x92, 0x1f, 0x63,
	0x97, 0xbc, 0x9b, 0xb8, 0xa5, 0xd3, 0x89, 0x5b, 0xfa, 0x36, 0x71, 0x4b, 0x2f, 0x37, 0x82, 0x30,
	0xed, 0x0f, 0xf7, 0xbc, 0x9e, 0x8a, 0xb8, 0xbd, 0x4b, 0xcd, 0xf5, 0xda, 0xb2, 0xa5, 0xa3, 0x44,
	0xe2, 0x5e, 0x59, 0x9f, 0xdb, 0xf6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x23, 0xe3, 0x67,
	0x19, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// HasNonce checks whether a specific timestamp nonce has been consumed for an address.
	HasNonce(ctx context.Context, in *QueryHasNonceRequest, opts ...grpc.CallOption) (*QueryHasNonceResponse, error)
	// NoncesByAddress returns all active timestamp nonces for a given address.
	NoncesByAddress(ctx context.Context, in *QueryNoncesByAddressRequest, opts ...grpc.CallOption) (*QueryNoncesByAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/gaia.nonce.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HasNonce(ctx context.Context, in *QueryHasNonceRequest, opts ...grpc.CallOption) (*QueryHasNonceResponse, error) {
	out := new(QueryHasNonceResponse)
	err := c.cc.Invoke(ctx, "/gaia.nonce.v1.Query/HasNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NoncesByAddress(ctx context.Context, in *QueryNoncesByAddressRequest, opts ...grpc.CallOption) (*QueryNoncesByAddressResponse, error) {
	out := new(QueryNoncesByAddressResponse)
	err := c.cc.Invoke(ctx, "/gaia.nonce.v1.Query/NoncesByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// HasNonce checks whether a specific timestamp nonce has been consumed for an address.
	HasNonce(context.Context, *QueryHasNonceRequest) (*QueryHasNonceResponse, error)
	// NoncesByAddress returns all active timestamp nonces for a given address.
	NoncesByAddress(context.Context, *QueryNoncesByAddressRequest) (*QueryNoncesByAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) HasNonce(ctx context.Context, req *QueryHasNonceRequest) (*QueryHasNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasNonce not implemented")
}
func (*UnimplementedQueryServer) NoncesByAddress(ctx context.Context, req *QueryNoncesByAddressRequest) (*QueryNoncesByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoncesByAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.nonce.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HasNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHasNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HasNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.nonce.v1.Query/HasNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HasNonce(ctx, req.(*QueryHasNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NoncesByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNoncesByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NoncesByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.nonce.v1.Query/NoncesByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NoncesByAddress(ctx, req.(*QueryNoncesByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.nonce.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "HasNonce",
			Handler:    _Query_HasNonce_Handler,
		},
		{
			MethodName: "NoncesByAddress",
			Handler:    _Query_NoncesByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaia/nonce/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryHasNonceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHasNonceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHasNonceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimestampUs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TimestampUs))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryHasNonceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHasNonceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHasNonceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HasNonce {
		i--
		if m.HasNonce {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryNoncesByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNoncesByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNoncesByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNoncesByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNoncesByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNoncesByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TimestampNonces) > 0 {
		dAtA3 := make([]byte, len(m.TimestampNonces)*10)
		var j2 int
		for _, num := range m.TimestampNonces {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintQuery(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryHasNonceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.TimestampUs != 0 {
		n += 1 + sovQuery(uint64(m.TimestampUs))
	}
	return n
}

func (m *QueryHasNonceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HasNonce {
		n += 2
	}
	return n
}

func (m *QueryNoncesByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNoncesByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TimestampNonces) > 0 {
		l = 0
		for _, e := range m.TimestampNonces {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHasNonceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHasNonceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHasNonceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampUs", wireType)
			}
			m.TimestampUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampUs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHasNonceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHasNonceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHasNonceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasNonce", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasNonce = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNoncesByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNoncesByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNoncesByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNoncesByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNoncesByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNoncesByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TimestampNonces = append(m.TimestampNonces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.TimestampNonces) == 0 {
					m.TimestampNonces = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TimestampNonces = append(m.TimestampNonces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampNonces", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
